name: Release to Docker Hub

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.17.4

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch required Go modules
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4.0.1
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}
          tag-custom: latest
          tag-semver: |
            {{raw}}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
